name: Backend Tests

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - run: uv sync --all-extras
      - run: uv run pytest
